from django.urls import path
from django.utils.translation import gettext_lazy as _

from .views.category_views import (
    CategoryCreateDismissView,
    CategoryCreateView,
    CategoryDeleteView,
    CategoryDetailView,
    CategoryListView,
    CategoryUpdateDismissView,
    CategoryUpdateView,
    IntroTemplateView,
)
from .views.location_views import (
    LocationCreateView,
    LocationDeleteView,
    LocationDetailView,
    LocationListView,
    LocationResetOriginView,
    LocationUpdateView,
)

app_name = "djupkeep"
urlpatterns = [
    path(
        "",
        IntroTemplateView.as_view(),
        name="introduction",
    ),
    path(
        _("location/list/"),
        LocationListView.as_view(),
        name="location_list",
    ),
    path(
        _("location/add/"),
        LocationCreateView.as_view(),
        name="location_create",
    ),
    path(
        _("location/<pk>/"),
        LocationDetailView.as_view(),
        name="location_detail",
    ),
    path(
        _("location/<pk>/change/"),
        LocationUpdateView.as_view(),
        name="location_change",
    ),
    path(
        _("location/<pk>/reset-origin/"),
        LocationResetOriginView.as_view(),
        name="location_reset_origin",
    ),
    path(
        _("location/<pk>/delete/"),
        LocationDeleteView.as_view(),
        name="location_delete",
    ),
    path(
        _("category/list/"),
        CategoryListView.as_view(),
        name="category_list",
    ),
    path(
        "category/add/",
        CategoryCreateView.as_view(),
        name="category_create",
    ),
    path(
        "category/add/dismiss/",
        CategoryCreateDismissView.as_view(),
        name="category_create_dismiss",
    ),
    path(
        "category/<pk>/",
        CategoryDetailView.as_view(),
        name="category_detail",
    ),
    path(
        "category/<pk>/change/",
        CategoryUpdateView.as_view(),
        name="category_update",
    ),
    path(
        "category/<pk>/change/dismiss/",
        CategoryUpdateDismissView.as_view(),
        name="category_update_dismiss",
    ),
    path(
        "category/<pk>/delete/",
        CategoryDeleteView.as_view(),
        name="category_delete",
    ),
]
