# Generated by Django 4.1.5 on 2023-01-16 18:15

import djgeojson.fields
import filebrowser.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Name of the project",
                        max_length=50,
                        verbose_name="Name",
                    ),
                ),
                ("intro", models.TextField(null=True, verbose_name="Description")),
                (
                    "fb_image",
                    filebrowser.fields.FileBrowseField(
                        max_length=200, null=True, verbose_name="Image"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=200,
                        null=True,
                        upload_to="uploads/images/upkeep/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "origin",
                    djgeojson.fields.PointField(
                        null=True, verbose_name="Origin of axis"
                    ),
                ),
                (
                    "unit",
                    djgeojson.fields.PointField(null=True, verbose_name="Unit length"),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
