# Generated by Django 4.1.5 on 2023-01-19 17:43

import filebrowser.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="fb_image",
            field=filebrowser.fields.FileBrowseField(
                help_text="Plan of your project",
                max_length=200,
                null=True,
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Plan of your project",
                max_length=200,
                null=True,
                upload_to="uploads/images/upkeep/",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="intro",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
    ]
