# Generated by Django 4.1.5 on 2023-01-20 23:36

import djgeojson.fields
import filebrowser.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0002_alter_project_fb_image_alter_project_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "intro",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "fb_image",
                    filebrowser.fields.FileBrowseField(
                        help_text="Plan of your location",
                        max_length=200,
                        null=True,
                        verbose_name="Plan",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Plan of your location",
                        max_length=200,
                        null=True,
                        upload_to="uploads/images/upkeep/",
                        verbose_name="Plan",
                    ),
                ),
                (
                    "origin",
                    djgeojson.fields.PointField(
                        null=True, verbose_name="Origin of axis"
                    ),
                ),
                (
                    "unit",
                    djgeojson.fields.PointField(null=True, verbose_name="Unit length"),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
