# Generated by Django 4.1.5 on 2023-01-29 17:12

import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0004_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="length",
            field=djgeojson.fields.LineStringField(
                blank=True, null=True, verbose_name="Reference length on the map"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="meters",
            field=models.FloatField(
                default=1, verbose_name="Reference length in meters"
            ),
        ),
    ]
