# Generated by Django 4.1.5 on 2023-01-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0005_location_length_location_meters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="unit",
        ),
    ]
