# Generated by Django 4.1.5 on 2023-01-31 12:01

import djgeojson.fields
from django.db import migrations

import djupkeep.models


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0006_remove_location_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="length",
            field=djgeojson.fields.LineStringField(
                default=djupkeep.models.get_default_length_field,
                verbose_name="Reference length on the map",
            ),
        ),
    ]
