# Generated by Django 4.1.5 on 2023-02-01 19:27

import django.db.models.deletion
import djgeojson.fields
import filebrowser.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0008_alter_location_length_alter_location_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "fb_image",
                    filebrowser.fields.FileBrowseField(
                        max_length=200, null=True, verbose_name="Image"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=200,
                        null=True,
                        upload_to="uploads/images/upkeep/",
                        verbose_name="Image",
                    ),
                ),
                ("geom", djgeojson.fields.PointField(verbose_name="Position")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="djupkeep.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="djupkeep.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Element",
                "verbose_name_plural": "Elements",
            },
        ),
    ]
