# Generated by Django 4.1.5 on 2023-02-01 19:50

import djgeojson.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0009_element"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="geom",
            field=djgeojson.fields.PointField(null=True, verbose_name="Position"),
        ),
    ]
