# Generated by Django 4.1.5 on 2023-02-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0011_activity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["position", "title"],
                "verbose_name": "Element category",
                "verbose_name_plural": "Element categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
