# Generated by Django 4.1.5 on 2023-02-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0012_alter_category_options_category_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
