# Generated by Django 4.1.5 on 2023-02-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0013_activity_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["category", "position"],
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["position"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("30", "Monthly"),
                    ("60", "Bimonthly"),
                    ("90", "Quarterly"),
                    ("120", "Four-monthly"),
                    ("183", "Biannual"),
                    ("365", "Annual"),
                ],
                default="30",
                max_length=3,
            ),
        ),
    ]
