# Generated by Django 4.1.5 on 2023-02-14 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("djupkeep", "0014_alter_activity_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("7", "Weekly"),
                    ("30", "Monthly"),
                    ("60", "Bimonthly"),
                    ("90", "Quarterly"),
                    ("120", "Four-monthly"),
                    ("183", "Biannual"),
                    ("365", "Annual"),
                ],
                default="30",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField(null=True, verbose_name="Due date")),
                (
                    "check_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check date"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="djupkeep.activity",
                        verbose_name="Activity",
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="djupkeep.element",
                        verbose_name="Element",
                    ),
                ),
                (
                    "maintainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Maintainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["element", "-due_date"],
            },
        ),
    ]
