# Generated by Django 4.1.5 on 2023-02-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0015_alter_activity_frequency_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["element", "-due_date"],
                "permissions": [
                    ("check_task", "Can perform activity tasks on elements")
                ],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
