# Generated by Django 4.1.5 on 2023-02-21 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeocad", "0016_drawing_designx_drawing_designy_alter_insertion_geom"),
        ("djupkeep", "0016_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["due_date"],
                "permissions": [
                    ("check_task", "Can perform activity tasks on elements")
                ],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="drawing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="djeocad.drawing",
                verbose_name="Drawing",
            ),
        ),
    ]
