# Generated by Django 4.1.5 on 2023-02-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0017_alter_task_options_location_drawing"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="extend",
            field=models.BooleanField(
                default=False, verbose_name="Apply to subcategories only"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="read",
            field=models.BooleanField(
                default=False, verbose_name="Notes have been read"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("7", "Weekly"),
                    ("30", "Monthly"),
                    ("60", "Bimonthly"),
                    ("90", "Quarterly"),
                    ("120", "Four-monthly"),
                    ("183", "Biannual"),
                    ("365", "Annual"),
                    ("730", "Every two years"),
                ],
                default="30",
                max_length=3,
            ),
        ),
    ]
