# Generated by Django 4.1.5 on 2023-02-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0018_activity_extend_task_read_alter_activity_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="once",
            field=models.BooleanField(default=False, verbose_name="Apply only once"),
        ),
        migrations.AddField(
            model_name="activity",
            name="repeat",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
