# Generated by Django 4.1.5 on 2023-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djupkeep", "0001_squashed_0019_activity_once_activity_repeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Eventually add image to notes",
                max_length=200,
                null=True,
                upload_to="uploads/images/upkeep/",
                verbose_name="Image",
            ),
        ),
    ]
